import { Group, Match, StandingEntry } from "./types";

export const MOCK_DATA_VERSION = '2.4'; // Increment this to force a reset of localStorage

export const GIRONI: Group[] = [
  { id: 'girone-a', name: 'Girone A' },
  { id: 'girone-b', name: 'Girone B' },
  { id: 'girone-c', name: 'Girone C' },
  { id: 'girone-d', name: 'Girone D' },
  { id: 'girone-e', name: 'Girone E' },
  { id: 'girone-f', name: 'Girone F' },
  { id: 'girone-g', name: 'Girone G' },
  { id: 'girone-h', name: 'Girone H' },
  { id: 'girone-i', name: 'Girone I' },
  { id: 'girone-l', name: 'Girone L' },
];

export const MOCK_STANDINGS: Record<string, StandingEntry[]> = {
  'girone-a': [
    { teamId: 'a1', teamName: 'CASTELLANA BASKET CASTEL S.GIO', points: 30, played: 15, won: 15, lost: 0, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'a2', teamName: 'BASKET PODENZANO', points: 20, played: 15, won: 10, lost: 5, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'a3', teamName: 'BAKERY PIACENZA CLUB RED', points: 16, played: 15, won: 8, lost: 7, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'a4', teamName: "PROVILLANOVA VILL. SULL'ARDA", points: 16, played: 15, won: 8, lost: 7, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'a5', teamName: 'BASKET SALSO', points: 16, played: 15, won: 8, lost: 7, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'a6', teamName: 'FOX BASKET PARMA', points: 14, played: 15, won: 7, lost: 8, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'a7', teamName: 'SORBOLO BASKET SCHOOL', points: 8, played: 15, won: 4, lost: 11, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'a8', teamName: 'POL. VII CASTELLI GAZZOLESI', points: 6, played: 15, won: 3, lost: 12, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'a9', teamName: 'BAKERY BASKET CLUB PC WHITE', points: 0, played: 15, won: 0, lost: 15, pointsFor: 0, pointsAgainst: 0 },
  ],
  'girone-b': [
    { teamId: 'b1', teamName: 'BASKET MATILDICO QUATTRO CASTE', points: 26, played: 15, won: 13, lost: 2, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'b2', teamName: 'VIRTUS CASALGRANDE', points: 22, played: 15, won: 11, lost: 4, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'b3', teamName: "POL. L'ARENA 'A' MONTECCHIO EM", points: 20, played: 15, won: 10, lost: 5, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'b4', teamName: 'REAL CASINA 04', points: 20, played: 15, won: 10, lost: 5, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'b5', teamName: "POL. L'ARENA 'B' MONTECCHIO EM", points: 20, played: 15, won: 10, lost: 5, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'b6', teamName: 'GO BASKET 2018 QUATTRO CASTELL', points: 16, played: 15, won: 8, lost: 7, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'b7', teamName: 'ALBINEA HILLS', points: 12, played: 15, won: 6, lost: 9, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'b8', teamName: "POL. L'ARENA 'C' MONTECCHIO EM", points: 6, played: 15, won: 3, lost: 12, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'b9', teamName: 'CASTELLARANO BASKETBALL', points: 6, played: 15, won: 3, lost: 12, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'b10', teamName: 'POL. ICARE CAVRIAGO', points: 4, played: 15, won: 2, lost: 13, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'b11', teamName: 'SAMPOLESE BK E VOLLEY', points: 4, played: 15, won: 2, lost: 13, pointsFor: 0, pointsAgainst: 0 },
  ],
  'girone-c': [
    { teamId: 'c1', teamName: 'FENICE BASKET', points: 26, played: 15, won: 13, lost: 2, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'c2', teamName: 'MARCONI BASKET CASTELNOVO DI S', points: 24, played: 15, won: 12, lost: 3, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'c3', teamName: "LA TORRE RE 'B'", points: 24, played: 15, won: 12, lost: 3, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'c4', teamName: 'U.S. REGGIO EMILIA', points: 16, played: 15, won: 8, lost: 7, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'c5', teamName: 'GELSO REGGIO EMILIA', points: 16, played: 15, won: 8, lost: 7, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'c6', teamName: 'AUDAX POVIGLIO 2011', points: 16, played: 15, won: 8, lost: 7, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'c7', teamName: 'BASKET FABBRICO', points: 10, played: 15, won: 5, lost: 10, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'c8', teamName: "LA TORRE RE 'A'", points: 8, played: 15, won: 4, lost: 11, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'c9', teamName: 'S. ILARIO BASKETVOLLEY', points: 6, played: 15, won: 3, lost: 12, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'c10', teamName: 'POL. AIRONI GUALTIERI', points: 4, played: 15, won: 2, lost: 13, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'c11', teamName: 'ARBOR BASKET RE', points: 2, played: 15, won: 1, lost: 14, pointsFor: 0, pointsAgainst: 0 },
  ],
  'girone-d': [
    { teamId: 'd1', teamName: 'S. FRANCESCO SMILE FORMIGINE', points: 28, played: 18, won: 14, lost: 4, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'd2', teamName: 'BASKET MAGRETA', points: 28, played: 18, won: 14, lost: 4, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'd3', teamName: 'POL. MONTEVEGLIO', points: 24, played: 18, won: 12, lost: 6, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'd4', teamName: 'SCUOLA PALL. SPILAMBERTO', points: 20, played: 18, won: 10, lost: 8, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'd5', teamName: 'JAILBREAKERS VIGNOLA', points: 18, played: 18, won: 9, lost: 9, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'd6', teamName: 'BK POL. CASTELFRANCO E.', points: 18, played: 18, won: 9, lost: 9, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'd7', teamName: 'SCHIOCCHI VETERANS SASSUOLO', points: 8, played: 18, won: 4, lost: 14, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'd8', teamName: 'PAVULLO BASKET', points: 6, played: 18, won: 3, lost: 15, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'd9', teamName: 'PALL. SASSUOLO U20', points: 8, played: 18, won: 4, lost: 14, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'd10', teamName: 'POL. MARANELLO', points: 4, played: 18, won: 2, lost: 16, pointsFor: 0, pointsAgainst: 0 },
  ],
  'girone-e': [
    { teamId: 'e1', teamName: 'VIS CLIPPERS S.G.PERSICETO', points: 32, played: 18, won: 16, lost: 2, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'e2', teamName: 'CARPINE BASKET 2015 CARPI', points: 24, played: 18, won: 12, lost: 6, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'e3', teamName: 'ESERCITO ACCADEMIA MILITARE MO', points: 24, played: 18, won: 12, lost: 6, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'e4', teamName: 'PALL. TEAM MEDOLLA', points: 18, played: 18, won: 9, lost: 9, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'e5', teamName: 'POL. NAZARENO CARPI', points: 18, played: 18, won: 9, lost: 9, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'e6', teamName: 'MODENA HOOPS', points: 18, played: 18, won: 9, lost: 9, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'e7', teamName: 'SASSO BASKET CASTELFRANCO', points: 12, played: 18, won: 6, lost: 12, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'e8', teamName: 'BASKET NOVI', points: 10, played: 18, won: 5, lost: 13, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'e9', teamName: 'MODENA BASKET', points: 8, played: 18, won: 4, lost: 14, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'e10', teamName: 'MOBA LAB MODENA', points: 2, played: 18, won: 1, lost: 17, pointsFor: 0, pointsAgainst: 0 },
  ],
  'girone-f': [
    { teamId: 'f1', teamName: 'VIS 2008 FERRARA', points: 28, played: 15, won: 14, lost: 1, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'f2', teamName: 'GALLIERA LOVERS', points: 22, played: 15, won: 11, lost: 4, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'f3', teamName: 'DESPAR 4 TORRI FERRARA', points: 20, played: 15, won: 10, lost: 5, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'f4', teamName: 'PALL. MOLINELLA', points: 18, played: 15, won: 9, lost: 6, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'f5', teamName: 'GRUPPO RAVIOLE CENTO', points: 16, played: 15, won: 8, lost: 7, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'f6', teamName: 'BASKET ESTENSE 2011', points: 16, played: 15, won: 8, lost: 7, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'f7', teamName: 'ANTARES BASKET COPPARO', points: 14, played: 15, won: 7, lost: 8, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'f8', teamName: 'BENEDETTO 1964 CENTO', points: 14, played: 15, won: 7, lost: 8, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'f9', teamName: 'MATILDE BASKET BONDENO', points: 8, played: 15, won: 4, lost: 11, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'f10', teamName: 'ACLI G 88 FERRARA', points: 6, played: 15, won: 3, lost: 12, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'f11', teamName: 'BASKET FINALE EMILIA', points: 2, played: 15, won: 1, lost: 14, pointsFor: 0, pointsAgainst: 0 },
  ],
  'girone-g': [
    { teamId: 'g1', teamName: 'POL. MONTE S.PIETRO', points: 30, played: 18, won: 15, lost: 3, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'g2', teamName: 'TROTTOLA PORRETTA BASKET', points: 28, played: 18, won: 14, lost: 4, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'g3', teamName: 'CSI SASSO MARCONI', points: 24, played: 18, won: 12, lost: 6, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'g4', teamName: 'R.D.G. ANTAL 59 BOLOGNA', points: 22, played: 18, won: 11, lost: 7, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'g5', teamName: 'G.B. INSPORT BOLOGNA', points: 20, played: 18, won: 10, lost: 8, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'g6', teamName: 'CVD BASKET CLUB BO', points: 18, played: 18, won: 9, lost: 9, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'g7', teamName: 'ANZOLA BASKET', points: 16, played: 18, won: 8, lost: 10, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'g8', teamName: 'CARLOTTA ZECCHI BK RENO BO', points: 12, played: 18, won: 6, lost: 12, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'g9', teamName: 'U.P. CALDERARA PALL.', points: 12, played: 18, won: 6, lost: 12, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'g10', teamName: "SALUS PALL. BOLOGNA 'A'", points: 8, played: 18, won: 4, lost: 14, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'g11', teamName: 'SALUS PALL. BOLOGNA', points: 6, played: 18, won: 3, lost: 15, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'g12', teamName: 'POL. G. VERGATESE F.LLI ZANI', points: 0, played: 18, won: 0, lost: 18, pointsFor: 0, pointsAgainst: 0 },
  ],
  'girone-h': [
    { teamId: 'PALL. BUDRIO', teamName: 'PALL. BUDRIO', points: 32, played: 17, won: 16, lost: 1, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'PALL. CASTEL S.P.T. 2010', teamName: 'PALL. CASTEL S.P.T. 2010', points: 30, played: 17, won: 15, lost: 2, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'P.G.S. CORTICELLA BO', teamName: 'P.G.S. CORTICELLA BO', points: 26, played: 18, won: 13, lost: 5, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'REUNION BOLOGNA', teamName: 'REUNION BOLOGNA', points: 22, played: 17, won: 11, lost: 6, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'NAVILE BASKET BOLOGNA', teamName: 'NAVILE BASKET BOLOGNA', points: 20, played: 17, won: 10, lost: 7, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'STARS BASKET BOLOGNA', teamName: 'STARS BASKET BOLOGNA', points: 16, played: 17, won: 8, lost: 9, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'PGS-IMA BOLOGNA', teamName: 'PGS-IMA BOLOGNA', points: 14, played: 16, won: 7, lost: 9, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'BASKET VILLAGE GRANAROLO E.', teamName: 'BASKET VILLAGE GRANAROLO E.', points: 14, played: 18, won: 7, lost: 11, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'CLATERNA \'B\' OZZANO E.', teamName: 'CLATERNA \'B\' OZZANO E.', points: 12, played: 17, won: 6, lost: 11, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'UNDERGROUND MURRI BO', teamName: 'UNDERGROUND MURRI BO', points: 10, played: 16, won: 5, lost: 11, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'PROGRESSO HAPPY BKT \'07', teamName: 'PROGRESSO HAPPY BKT \'07', points: 8, played: 17, won: 4, lost: 13, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'THUNDER BASKET BO', teamName: 'THUNDER BASKET BO', points: 0, played: 17, won: 0, lost: 17, pointsFor: 0, pointsAgainst: 0 },
  ],
  'girone-i': [
    { teamId: 'i1', teamName: 'PLAYGROUND VOLTA DOZZA', points: 32, played: 18, won: 16, lost: 2, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'i2', teamName: 'ROBUR LUGO', points: 28, played: 18, won: 14, lost: 4, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'i3', teamName: 'TATANKA BALONCESTO IMOLA', points: 26, played: 18, won: 13, lost: 5, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'i4', teamName: 'BASKET A. GARDINI 2001 FUSIGNA', points: 18, played: 18, won: 9, lost: 9, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'i5', teamName: 'CSI SERVIZI IMOLA', points: 16, played: 18, won: 8, lost: 10, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'i6', teamName: "COMPAGNIA DELL'ALBERO RAVENNA", points: 14, played: 18, won: 7, lost: 11, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'i7', teamName: 'WARRIORS BASKET RAVENNA', points: 14, played: 18, won: 7, lost: 11, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'i8', teamName: 'BASKET 95 IMOLA', points: 12, played: 18, won: 6, lost: 12, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'i9', teamName: 'BASKET CASTELBOLOGNESE', points: 12, played: 18, won: 6, lost: 12, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'i10', teamName: 'GRIFO TEENAGERS IMOLA', points: 12, played: 18, won: 6, lost: 12, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'i11', teamName: 'BASKET CLUB RUSSI', points: 10, played: 18, won: 5, lost: 13, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'i12', teamName: 'FAENZA BASKET PROJECT', points: 4, played: 18, won: 2, lost: 16, pointsFor: 0, pointsAgainst: 0 },
  ],
  'girone-l': [
    { teamId: 'l1', teamName: 'BASKERS FORLIMPOPOLI', points: 30, played: 15, won: 15, lost: 0, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'l2', teamName: "AICS JUNIOR BASKET FORLI'", points: 28, played: 15, won: 14, lost: 1, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'l3', teamName: 'EASY LINE PALL. CESENA 2.0', points: 26, played: 15, won: 13, lost: 2, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'l4', teamName: 'LIVIO NERI CESENA', points: 18, played: 15, won: 9, lost: 6, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'l5', teamName: "A.I.C.S. BASKET FORLI'", points: 18, played: 15, won: 9, lost: 6, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'l6', teamName: 'ARCOBALENO I COLORI DEL MOV. B', points: 14, played: 15, won: 7, lost: 8, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'l7', teamName: 'MISANO PIRATES', points: 10, played: 15, won: 5, lost: 10, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'l8', teamName: 'CATTOLICA NEXT GEN', points: 10, played: 15, won: 5, lost: 10, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'l9', teamName: 'AROUND SPORT SAVIGNANO S/RUBIC', points: 8, played: 15, won: 4, lost: 11, pointsFor: 0, pointsAgainst: 0 },
    { teamId: 'l10', teamName: 'E CRUSERI RAVENNA', points: 6, played: 15, won: 3, lost: 12, pointsFor: 0, pointsAgainst: 0 },
  ]
};

export const MOCK_MATCHES: Record<string, Match[]> = {
  'girone-a': [],
  'girone-b': [],
  'girone-c': [],
  'girone-d': [
    { id: 'd-m1', homeTeamId: 'PAVULLO BASKET', awayTeamId: 'SCHIOCCHI VETERANS SASSUOLO', homeScore: 47, awayScore: 52, date: '2026-03-17', time: '21:00', status: 'finished', mvpVotes: 0 },
    { id: 'd-m2', homeTeamId: 'POL. MONTEVEGLIO', awayTeamId: 'BK POL. CASTELFRANCO E.', date: '2026-03-18', time: '21:30', status: 'scheduled', mvpVotes: 0 },
    { id: 'd-m3', homeTeamId: 'JAILBREAKERS VIGNOLA', awayTeamId: 'SCUOLA PALL. SPILAMBERTO', date: '2026-03-19', time: '21:45', status: 'scheduled', mvpVotes: 0 },
    { id: 'd-m4', homeTeamId: 'S. FRANCESCO SMILE FORMIGINE', awayTeamId: 'PALL. SASSUOLO U20', date: '2026-03-20', time: '21:15', status: 'scheduled', mvpVotes: 0 },
    { id: 'd-m5', homeTeamId: 'BASKET MAGRETA', awayTeamId: 'POL. MARANELLO', date: '2026-03-23', time: '21:30', status: 'scheduled', mvpVotes: 0 },
  ],
  'girone-e': [],
  'girone-f': [],
  'girone-g': [],
  'girone-h': [
    // Giornata 1
    { id: 'h-m1', homeTeamId: 'REUNION BOLOGNA', awayTeamId: 'UNDERGROUND MURRI BO', homeScore: 73, awayScore: 55, date: '2025-11-06', time: '21:45', status: 'finished', mvpVotes: 0, matchday: 1 },
    { id: 'h-m2', homeTeamId: "PROGRESSO HAPPY BKT '07", awayTeamId: 'STARS BASKET BOLOGNA', homeScore: 78, awayScore: 48, date: '2025-11-06', time: '21:50', status: 'finished', mvpVotes: 0, matchday: 1 },
    { id: 'h-m3', homeTeamId: 'THUNDER BASKET BO', awayTeamId: 'PALL. CASTEL S.P.T. 2010', homeScore: 35, awayScore: 66, date: '2025-11-06', time: '22:00', status: 'finished', mvpVotes: 0, matchday: 1 },
    { id: 'h-m4', homeTeamId: 'PGS-IMA BOLOGNA', awayTeamId: 'BASKET VILLAGE GRANAROLO E.', homeScore: 55, awayScore: 56, date: '2025-11-07', time: '21:45', status: 'finished', mvpVotes: 0, matchday: 1 },
    { id: 'h-m5', homeTeamId: 'PALL. BUDRIO', awayTeamId: 'P.G.S. CORTICELLA BO', homeScore: 74, awayScore: 49, date: '2025-11-07', time: '21:45', status: 'finished', mvpVotes: 0, matchday: 1 },
    { id: 'h-m6', homeTeamId: 'NAVILE BASKET BOLOGNA', awayTeamId: "CLATERNA 'B' OZZANO E.", homeScore: 76, awayScore: 70, date: '2025-11-05', time: '21:45', status: 'finished', mvpVotes: 0, matchday: 1 },
    // Giornata 2
    { id: 'h-m7', homeTeamId: 'PALL. CASTEL S.P.T. 2010', awayTeamId: 'PALL. BUDRIO', homeScore: 61, awayScore: 46, date: '2025-11-12', time: '21:15', status: 'finished', mvpVotes: 0, matchday: 2 },
    { id: 'h-m8', homeTeamId: 'P.G.S. CORTICELLA BO', awayTeamId: "CLATERNA 'B' OZZANO E.", homeScore: 70, awayScore: 61, date: '2025-11-12', time: '21:15', status: 'finished', mvpVotes: 0, matchday: 2 },
    { id: 'h-m9', homeTeamId: 'BASKET VILLAGE GRANAROLO E.', awayTeamId: "PROGRESSO HAPPY BKT '07", homeScore: 50, awayScore: 68, date: '2025-11-14', time: '21:45', status: 'finished', mvpVotes: 0, matchday: 2 },
    { id: 'h-m10', homeTeamId: 'NAVILE BASKET BOLOGNA', awayTeamId: 'REUNION BOLOGNA', homeScore: 59, awayScore: 83, date: '2025-11-17', time: '21:45', status: 'finished', mvpVotes: 0, matchday: 2 },
    { id: 'h-m11', homeTeamId: 'STARS BASKET BOLOGNA', awayTeamId: 'THUNDER BASKET BO', homeScore: 59, awayScore: 54, date: '2025-11-18', time: '21:45', status: 'finished', mvpVotes: 0, matchday: 2 },
    { id: 'h-m12', homeTeamId: 'UNDERGROUND MURRI BO', awayTeamId: 'PGS-IMA BOLOGNA', date: '2026-04-03', time: '20:50', status: 'scheduled', mvpVotes: 0, matchday: 2 },
    // Giornata 3
    { id: 'h-m13', homeTeamId: 'P.G.S. CORTICELLA BO', awayTeamId: "PROGRESSO HAPPY BKT '07", homeScore: 78, awayScore: 65, date: '2025-11-19', time: '21:15', status: 'finished', mvpVotes: 0, matchday: 3 },
    { id: 'h-m14', homeTeamId: 'THUNDER BASKET BO', awayTeamId: 'NAVILE BASKET BOLOGNA', homeScore: 42, awayScore: 74, date: '2025-11-20', time: '22:00', status: 'finished', mvpVotes: 0, matchday: 3 },
    { id: 'h-m15', homeTeamId: "CLATERNA 'B' OZZANO E.", awayTeamId: 'PALL. BUDRIO', homeScore: 57, awayScore: 71, date: '2025-11-20', time: '21:00', status: 'finished', mvpVotes: 0, matchday: 3 },
    { id: 'h-m16', homeTeamId: 'REUNION BOLOGNA', awayTeamId: 'PGS-IMA BOLOGNA', homeScore: 69, awayScore: 68, date: '2025-11-20', time: '21:45', status: 'finished', mvpVotes: 0, matchday: 3 },
    { id: 'h-m17', homeTeamId: 'BASKET VILLAGE GRANAROLO E.', awayTeamId: 'STARS BASKET BOLOGNA', homeScore: 61, awayScore: 54, date: '2025-11-21', time: '21:45', status: 'finished', mvpVotes: 0, matchday: 3 },
    { id: 'h-m18', homeTeamId: 'UNDERGROUND MURRI BO', awayTeamId: 'PALL. CASTEL S.P.T. 2010', homeScore: 48, awayScore: 61, date: '2025-11-21', time: '20:50', status: 'finished', mvpVotes: 0, matchday: 3 },
    // Giornata 4
    { id: 'h-m19', homeTeamId: "PROGRESSO HAPPY BKT '07", awayTeamId: 'UNDERGROUND MURRI BO', homeScore: 47, awayScore: 56, date: '2025-11-25', time: '21:50', status: 'finished', mvpVotes: 0, matchday: 4 },
    { id: 'h-m20', homeTeamId: 'PALL. CASTEL S.P.T. 2010', awayTeamId: 'STARS BASKET BOLOGNA', homeScore: 64, awayScore: 48, date: '2025-11-26', time: '21:15', status: 'finished', mvpVotes: 0, matchday: 4 },
    { id: 'h-m21', homeTeamId: 'PGS-IMA BOLOGNA', awayTeamId: 'P.G.S. CORTICELLA BO', homeScore: 86, awayScore: 85, date: '2025-11-28', time: '21:45', status: 'finished', mvpVotes: 0, matchday: 4 },
    { id: 'h-m22', homeTeamId: 'PALL. BUDRIO', awayTeamId: 'NAVILE BASKET BOLOGNA', homeScore: 82, awayScore: 61, date: '2025-11-28', time: '21:45', status: 'finished', mvpVotes: 0, matchday: 4 },
    { id: 'h-m23', homeTeamId: 'THUNDER BASKET BO', awayTeamId: 'BASKET VILLAGE GRANAROLO E.', homeScore: 49, awayScore: 64, date: '2026-01-08', time: '21:45', status: 'finished', mvpVotes: 0, matchday: 4 },
    { id: 'h-m24', homeTeamId: "CLATERNA 'B' OZZANO E.", awayTeamId: 'REUNION BOLOGNA', homeScore: 65, awayScore: 56, date: '2026-01-17', time: '19:00', status: 'finished', mvpVotes: 0, matchday: 4 },
    // Giornata 5
    { id: 'h-m25', homeTeamId: 'BASKET VILLAGE GRANAROLO E.', awayTeamId: 'PALL. CASTEL S.P.T. 2010', homeScore: 51, awayScore: 78, date: '2025-12-03', time: '21:50', status: 'finished', mvpVotes: 0, matchday: 5 },
    { id: 'h-m26', homeTeamId: 'REUNION BOLOGNA', awayTeamId: 'THUNDER BASKET BO', homeScore: 68, awayScore: 42, date: '2025-12-04', time: '21:45', status: 'finished', mvpVotes: 0, matchday: 5 },
    { id: 'h-m27', homeTeamId: 'UNDERGROUND MURRI BO', awayTeamId: 'P.G.S. CORTICELLA BO', homeScore: 49, awayScore: 57, date: '2025-12-05', time: '20:50', status: 'finished', mvpVotes: 0, matchday: 5 },
    { id: 'h-m28', homeTeamId: 'PGS-IMA BOLOGNA', awayTeamId: "CLATERNA 'B' OZZANO E.", homeScore: 48, awayScore: 69, date: '2025-12-05', time: '21:45', status: 'finished', mvpVotes: 0, matchday: 5 },
    { id: 'h-m29', homeTeamId: "PROGRESSO HAPPY BKT '07", awayTeamId: 'NAVILE BASKET BOLOGNA', homeScore: 67, awayScore: 68, date: '2025-12-09', time: '21:50', status: 'finished', mvpVotes: 0, matchday: 5 },
    { id: 'h-m30', homeTeamId: 'STARS BASKET BOLOGNA', awayTeamId: 'PALL. BUDRIO', homeScore: 62, awayScore: 65, date: '2025-12-22', time: '21:30', status: 'finished', mvpVotes: 0, matchday: 5 },
    // Giornata 6
    { id: 'h-m31', homeTeamId: 'P.G.S. CORTICELLA BO', awayTeamId: 'STARS BASKET BOLOGNA', homeScore: 68, awayScore: 39, date: '2025-12-10', time: '21:15', status: 'finished', mvpVotes: 0, matchday: 6 },
    { id: 'h-m32', homeTeamId: 'THUNDER BASKET BO', awayTeamId: 'PGS-IMA BOLOGNA', homeScore: 44, awayScore: 55, date: '2025-12-11', time: '22:00', status: 'finished', mvpVotes: 0, matchday: 6 },
    { id: 'h-m33', homeTeamId: 'REUNION BOLOGNA', awayTeamId: 'PALL. CASTEL S.P.T. 2010', homeScore: 45, awayScore: 60, date: '2025-12-11', time: '21:45', status: 'finished', mvpVotes: 0, matchday: 6 },
    { id: 'h-m34', homeTeamId: 'PALL. BUDRIO', awayTeamId: "PROGRESSO HAPPY BKT '07", homeScore: 89, awayScore: 49, date: '2025-12-12', time: '21:45', status: 'finished', mvpVotes: 0, matchday: 6 },
    { id: 'h-m35', homeTeamId: 'NAVILE BASKET BOLOGNA', awayTeamId: 'UNDERGROUND MURRI BO', homeScore: 57, awayScore: 55, date: '2025-12-15', time: '21:45', status: 'finished', mvpVotes: 0, matchday: 6 },
    { id: 'h-m36', homeTeamId: "CLATERNA 'B' OZZANO E.", awayTeamId: 'BASKET VILLAGE GRANAROLO E.', homeScore: 69, awayScore: 39, date: '2026-02-03', time: '21:30', status: 'finished', mvpVotes: 0, matchday: 6 },
    // Giornata 7
    { id: 'h-m37', homeTeamId: "PROGRESSO HAPPY BKT '07", awayTeamId: 'THUNDER BASKET BO', homeScore: 53, awayScore: 43, date: '2025-12-16', time: '21:50', status: 'finished', mvpVotes: 0, matchday: 7 },
    { id: 'h-m38', homeTeamId: 'PALL. CASTEL S.P.T. 2010', awayTeamId: "CLATERNA 'B' OZZANO E.", homeScore: 76, awayScore: 28, date: '2025-12-17', time: '21:15', status: 'finished', mvpVotes: 0, matchday: 7 },
    { id: 'h-m39', homeTeamId: 'REUNION BOLOGNA', awayTeamId: 'PALL. BUDRIO', homeScore: 70, awayScore: 84, date: '2025-12-18', time: '21:45', status: 'finished', mvpVotes: 0, matchday: 7 },
    { id: 'h-m40', homeTeamId: 'BASKET VILLAGE GRANAROLO E.', awayTeamId: 'P.G.S. CORTICELLA BO', homeScore: 61, awayScore: 70, date: '2025-12-19', time: '21:30', status: 'finished', mvpVotes: 0, matchday: 7 },
    { id: 'h-m41', homeTeamId: 'UNDERGROUND MURRI BO', awayTeamId: 'STARS BASKET BOLOGNA', homeScore: 55, awayScore: 62, date: '2025-12-19', time: '20:50', status: 'finished', mvpVotes: 0, matchday: 7 },
    { id: 'h-m42', homeTeamId: 'PGS-IMA BOLOGNA', awayTeamId: 'NAVILE BASKET BOLOGNA', homeScore: 73, awayScore: 65, date: '2026-01-30', time: '21:45', status: 'finished', mvpVotes: 0, matchday: 7 },
    // Giornata 8
    { id: 'h-m43', homeTeamId: 'REUNION BOLOGNA', awayTeamId: "PROGRESSO HAPPY BKT '07", homeScore: 55, awayScore: 54, date: '2026-01-08', time: '21:45', status: 'finished', mvpVotes: 0, matchday: 8 },
    { id: 'h-m44', homeTeamId: 'PGS-IMA BOLOGNA', awayTeamId: 'PALL. BUDRIO', homeScore: 71, awayScore: 90, date: '2026-01-09', time: '21:45', status: 'finished', mvpVotes: 0, matchday: 8 },
    { id: 'h-m45', homeTeamId: 'P.G.S. CORTICELLA BO', awayTeamId: 'PALL. CASTEL S.P.T. 2010', homeScore: 54, awayScore: 63, date: '2026-01-09', time: '21:30', status: 'finished', mvpVotes: 0, matchday: 8 },
    { id: 'h-m46', homeTeamId: 'BASKET VILLAGE GRANAROLO E.', awayTeamId: 'UNDERGROUND MURRI BO', homeScore: 63, awayScore: 52, date: '2026-01-13', time: '21:50', status: 'finished', mvpVotes: 0, matchday: 8 },
    { id: 'h-m47', homeTeamId: 'STARS BASKET BOLOGNA', awayTeamId: 'NAVILE BASKET BOLOGNA', homeScore: 54, awayScore: 55, date: '2026-01-15', time: '21:45', status: 'finished', mvpVotes: 0, matchday: 8 },
    { id: 'h-m48', homeTeamId: "CLATERNA 'B' OZZANO E.", awayTeamId: 'THUNDER BASKET BO', homeScore: 59, awayScore: 34, date: '2026-01-30', time: '21:30', status: 'finished', mvpVotes: 0, matchday: 8 },
    // Giornata 9
    { id: 'h-m49', homeTeamId: "PROGRESSO HAPPY BKT '07", awayTeamId: 'PALL. CASTEL S.P.T. 2010', homeScore: 52, awayScore: 87, date: '2026-01-13', time: '21:50', status: 'finished', mvpVotes: 0, matchday: 9 },
    { id: 'h-m50', homeTeamId: 'P.G.S. CORTICELLA BO', awayTeamId: 'REUNION BOLOGNA', homeScore: 67, awayScore: 68, date: '2026-01-14', time: '21:15', status: 'finished', mvpVotes: 0, matchday: 9 },
    { id: 'h-m51', homeTeamId: "CLATERNA 'B' OZZANO E.", awayTeamId: 'UNDERGROUND MURRI BO', homeScore: 45, awayScore: 49, date: '2026-01-15', time: '21:30', status: 'finished', mvpVotes: 0, matchday: 9 },
    { id: 'h-m52', homeTeamId: 'THUNDER BASKET BO', awayTeamId: 'PALL. BUDRIO', homeScore: 44, awayScore: 70, date: '2026-01-15', time: '22:00', status: 'finished', mvpVotes: 0, matchday: 9 },
    { id: 'h-m53', homeTeamId: 'NAVILE BASKET BOLOGNA', awayTeamId: 'BASKET VILLAGE GRANAROLO E.', homeScore: 63, awayScore: 65, date: '2026-01-19', time: '21:45', status: 'finished', mvpVotes: 0, matchday: 9 },
    { id: 'h-m54', homeTeamId: 'STARS BASKET BOLOGNA', awayTeamId: 'PGS-IMA BOLOGNA', homeScore: 77, awayScore: 64, date: '2026-01-20', time: '21:45', status: 'finished', mvpVotes: 0, matchday: 9 },
    // Giornata 10
    { id: 'h-m55', homeTeamId: 'REUNION BOLOGNA', awayTeamId: 'STARS BASKET BOLOGNA', homeScore: 72, awayScore: 61, date: '2026-01-22', time: '21:45', status: 'finished', mvpVotes: 0, matchday: 10 },
    { id: 'h-m56', homeTeamId: "CLATERNA 'B' OZZANO E.", awayTeamId: "PROGRESSO HAPPY BKT '07", homeScore: 78, awayScore: 56, date: '2026-01-22', time: '21:30', status: 'finished', mvpVotes: 0, matchday: 10 },
    { id: 'h-m57', homeTeamId: 'THUNDER BASKET BO', awayTeamId: 'UNDERGROUND MURRI BO', homeScore: 49, awayScore: 59, date: '2026-01-22', time: '22:00', status: 'finished', mvpVotes: 0, matchday: 10 },
    { id: 'h-m58', homeTeamId: 'PGS-IMA BOLOGNA', awayTeamId: 'PALL. CASTEL S.P.T. 2010', homeScore: 58, awayScore: 70, date: '2026-01-23', time: '21:45', status: 'finished', mvpVotes: 0, matchday: 10 },
    { id: 'h-m59', homeTeamId: 'NAVILE BASKET BOLOGNA', awayTeamId: 'P.G.S. CORTICELLA BO', homeScore: 73, awayScore: 78, date: '2026-01-26', time: '21:45', status: 'finished', mvpVotes: 0, matchday: 10 },
    { id: 'h-m60', homeTeamId: 'BASKET VILLAGE GRANAROLO E.', awayTeamId: 'PALL. BUDRIO', homeScore: 49, awayScore: 96, date: '2026-01-28', time: '21:40', status: 'finished', mvpVotes: 0, matchday: 10 },
    // Giornata 11
    { id: 'h-m61', homeTeamId: 'STARS BASKET BOLOGNA', awayTeamId: "CLATERNA 'B' OZZANO E.", homeScore: 59, awayScore: 76, date: '2026-01-26', time: '21:45', status: 'finished', mvpVotes: 0, matchday: 11 },
    { id: 'h-m62', homeTeamId: "PROGRESSO HAPPY BKT '07", awayTeamId: 'PGS-IMA BOLOGNA', homeScore: 53, awayScore: 73, date: '2026-01-27', time: '21:50', status: 'finished', mvpVotes: 0, matchday: 11 },
    { id: 'h-m63', homeTeamId: 'P.G.S. CORTICELLA BO', awayTeamId: 'THUNDER BASKET BO', homeScore: 74, awayScore: 60, date: '2026-01-28', time: '21:15', status: 'finished', mvpVotes: 0, matchday: 11 },
    { id: 'h-m64', homeTeamId: 'PALL. BUDRIO', awayTeamId: 'UNDERGROUND MURRI BO', homeScore: 72, awayScore: 56, date: '2026-01-30', time: '21:45', status: 'finished', mvpVotes: 0, matchday: 11 },
    { id: 'h-m65', homeTeamId: 'BASKET VILLAGE GRANAROLO E.', awayTeamId: 'REUNION BOLOGNA', homeScore: 45, awayScore: 78, date: '2026-01-30', time: '21:45', status: 'finished', mvpVotes: 0, matchday: 11 },
    { id: 'h-m66', homeTeamId: 'PALL. CASTEL S.P.T. 2010', awayTeamId: 'NAVILE BASKET BOLOGNA', homeScore: 71, awayScore: 51, date: '2026-02-16', time: '21:15', status: 'finished', mvpVotes: 0, matchday: 11 },
    // Giornata 12
    { id: 'h-m67', homeTeamId: 'P.G.S. CORTICELLA BO', awayTeamId: 'PALL. BUDRIO', homeScore: 42, awayScore: 82, date: '2026-02-04', time: '21:15', status: 'finished', mvpVotes: 0, matchday: 12 },
    { id: 'h-m68', homeTeamId: 'PALL. CASTEL S.P.T. 2010', awayTeamId: 'THUNDER BASKET BO', homeScore: 72, awayScore: 30, date: '2026-02-04', time: '21:15', status: 'finished', mvpVotes: 0, matchday: 12 },
    { id: 'h-m69', homeTeamId: "CLATERNA 'B' OZZANO E.", awayTeamId: 'NAVILE BASKET BOLOGNA', homeScore: 56, awayScore: 59, date: '2026-02-05', time: '21:30', status: 'finished', mvpVotes: 0, matchday: 12 },
    { id: 'h-m70', homeTeamId: 'UNDERGROUND MURRI BO', awayTeamId: 'REUNION BOLOGNA', homeScore: 50, awayScore: 53, date: '2026-02-06', time: '20:50', status: 'finished', mvpVotes: 0, matchday: 12 },
    { id: 'h-m71', homeTeamId: 'BASKET VILLAGE GRANAROLO E.', awayTeamId: 'PGS-IMA BOLOGNA', homeScore: 60, awayScore: 66, date: '2026-02-06', time: '21:45', status: 'finished', mvpVotes: 0, matchday: 12 },
    { id: 'h-m72', homeTeamId: 'STARS BASKET BOLOGNA', awayTeamId: "PROGRESSO HAPPY BKT '07", homeScore: 64, awayScore: 56, date: '2026-02-10', time: '21:45', status: 'finished', mvpVotes: 0, matchday: 12 },
    // Giornata 13
    { id: 'h-m73', homeTeamId: "CLATERNA 'B' OZZANO E.", awayTeamId: 'P.G.S. CORTICELLA BO', homeScore: 66, awayScore: 75, date: '2026-02-12', time: '21:30', status: 'finished', mvpVotes: 0, matchday: 13 },
    { id: 'h-m74', homeTeamId: 'REUNION BOLOGNA', awayTeamId: 'NAVILE BASKET BOLOGNA', homeScore: 70, awayScore: 75, date: '2026-02-12', time: '21:45', status: 'finished', mvpVotes: 0, matchday: 13 },
    { id: 'h-m75', homeTeamId: "PROGRESSO HAPPY BKT '07", awayTeamId: 'BASKET VILLAGE GRANAROLO E.', homeScore: 43, awayScore: 47, date: '2026-02-12', time: '21:50', status: 'finished', mvpVotes: 0, matchday: 13 },
    { id: 'h-m76', homeTeamId: 'THUNDER BASKET BO', awayTeamId: 'STARS BASKET BOLOGNA', homeScore: 33, awayScore: 55, date: '2026-02-12', time: '22:00', status: 'finished', mvpVotes: 0, matchday: 13 },
    { id: 'h-m77', homeTeamId: 'PGS-IMA BOLOGNA', awayTeamId: 'UNDERGROUND MURRI BO', homeScore: 63, awayScore: 65, date: '2026-02-13', time: '21:45', status: 'finished', mvpVotes: 0, matchday: 13 },
    { id: 'h-m78', homeTeamId: 'PALL. BUDRIO', awayTeamId: 'PALL. CASTEL S.P.T. 2010', homeScore: 72, awayScore: 50, date: '2026-02-13', time: '21:45', status: 'finished', mvpVotes: 0, matchday: 13 },
    // Giornata 14
    { id: 'h-m79', homeTeamId: "PROGRESSO HAPPY BKT '07", awayTeamId: 'P.G.S. CORTICELLA BO', homeScore: 43, awayScore: 65, date: '2026-02-17', time: '21:50', status: 'finished', mvpVotes: 0, matchday: 14 },
    { id: 'h-m80', homeTeamId: 'PGS-IMA BOLOGNA', awayTeamId: 'REUNION BOLOGNA', homeScore: 86, awayScore: 83, date: '2026-02-20', time: '21:45', status: 'finished', mvpVotes: 0, matchday: 14 },
    { id: 'h-m81', homeTeamId: 'PALL. BUDRIO', awayTeamId: "CLATERNA 'B' OZZANO E.", homeScore: 81, awayScore: 50, date: '2026-02-20', time: '21:45', status: 'finished', mvpVotes: 0, matchday: 14 },
    { id: 'h-m82', homeTeamId: 'NAVILE BASKET BOLOGNA', awayTeamId: 'THUNDER BASKET BO', homeScore: 57, awayScore: 53, date: '2026-02-23', time: '21:45', status: 'finished', mvpVotes: 0, matchday: 14 },
    { id: 'h-m83', homeTeamId: 'STARS BASKET BOLOGNA', awayTeamId: 'BASKET VILLAGE GRANAROLO E.', homeScore: 83, awayScore: 43, date: '2026-02-23', time: '21:30', status: 'finished', mvpVotes: 0, matchday: 14 },
    { id: 'h-m84', homeTeamId: 'PALL. CASTEL S.P.T. 2010', awayTeamId: 'UNDERGROUND MURRI BO', homeScore: 65, awayScore: 46, date: '2026-02-25', time: '21:15', status: 'finished', mvpVotes: 0, matchday: 14 },
    // Giornata 15
    { id: 'h-m85', homeTeamId: 'P.G.S. CORTICELLA BO', awayTeamId: 'PGS-IMA BOLOGNA', homeScore: 76, awayScore: 57, date: '2026-02-25', time: '21:15', status: 'finished', mvpVotes: 0, matchday: 15 },
    { id: 'h-m86', homeTeamId: 'UNDERGROUND MURRI BO', awayTeamId: 'NAVILE BASKET BOLOGNA', homeScore: 54, awayScore: 61, date: '2026-02-27', time: '20:50', status: 'finished', mvpVotes: 0, matchday: 15 },
    { id: 'h-m87', homeTeamId: 'BASKET VILLAGE GRANAROLO E.', awayTeamId: 'THUNDER BASKET BO', homeScore: 57, awayScore: 45, date: '2026-02-27', time: '21:45', status: 'finished', mvpVotes: 0, matchday: 15 },
    { id: 'h-m88', homeTeamId: 'PALL. BUDRIO', awayTeamId: "PROGRESSO HAPPY BKT '07", homeScore: 85, awayScore: 35, date: '2026-02-27', time: '21:45', status: 'finished', mvpVotes: 0, matchday: 15 },
    { id: 'h-m89', homeTeamId: 'REUNION BOLOGNA', awayTeamId: 'PALL. CASTEL S.P.T. 2010', homeScore: 64, awayScore: 55, date: '2026-02-26', time: '21:45', status: 'finished', mvpVotes: 0, matchday: 15 },
    { id: 'h-m90', homeTeamId: "CLATERNA 'B' OZZANO E.", awayTeamId: 'STARS BASKET BOLOGNA', homeScore: 60, awayScore: 63, date: '2026-02-26', time: '21:30', status: 'finished', mvpVotes: 0, matchday: 15 },
    // Giornata 16
    { id: 'h-m91', homeTeamId: 'P.G.S. CORTICELLA BO', awayTeamId: 'UNDERGROUND MURRI BO', homeScore: 54, awayScore: 47, date: '2026-03-04', time: '21:15', status: 'finished', mvpVotes: 0, matchday: 16 },
    { id: 'h-m92', homeTeamId: 'PALL. CASTEL S.P.T. 2010', awayTeamId: "CLATERNA 'B' OZZANO E.", homeScore: 73, awayScore: 51, date: '2026-03-04', time: '21:15', status: 'finished', mvpVotes: 0, matchday: 16 },
    { id: 'h-m93', homeTeamId: 'THUNDER BASKET BO', awayTeamId: "PROGRESSO HAPPY BKT '07", homeScore: 45, awayScore: 56, date: '2026-03-05', time: '22:00', status: 'finished', mvpVotes: 0, matchday: 16 },
    { id: 'h-m94', homeTeamId: 'REUNION BOLOGNA', awayTeamId: 'BASKET VILLAGE GRANAROLO E.', homeScore: 78, awayScore: 55, date: '2026-03-05', time: '21:45', status: 'finished', mvpVotes: 0, matchday: 16 },
    { id: 'h-m95', homeTeamId: 'NAVILE BASKET BOLOGNA', awayTeamId: 'PALL. BUDRIO', homeScore: 45, awayScore: 65, date: '2026-03-09', time: '21:45', status: 'finished', mvpVotes: 0, matchday: 16 },
    { id: 'h-m96', homeTeamId: 'STARS BASKET BOLOGNA', awayTeamId: 'PGS-IMA BOLOGNA', homeScore: 65, awayScore: 58, date: '2026-03-10', time: '21:45', status: 'finished', mvpVotes: 0, matchday: 16 },
    // Giornata 17
    { id: 'h-m97', homeTeamId: 'STARS BASKET BOLOGNA', awayTeamId: 'P.G.S. CORTICELLA BO', homeScore: 64, awayScore: 84, date: '2026-03-09', time: '21:45', status: 'finished', mvpVotes: 0, matchday: 17 },
    { id: 'h-m98', homeTeamId: 'PALL. BUDRIO', awayTeamId: 'REUNION BOLOGNA', homeScore: 75, awayScore: 55, date: '2026-03-13', time: '21:45', status: 'finished', mvpVotes: 0, matchday: 17 },
    { id: 'h-m99', homeTeamId: 'PGS-IMA BOLOGNA', awayTeamId: 'THUNDER BASKET BO', homeScore: 65, awayScore: 40, date: '2026-03-13', time: '21:45', status: 'finished', mvpVotes: 0, matchday: 17 },
    { id: 'h-m100', homeTeamId: "PROGRESSO HAPPY BKT '07", awayTeamId: 'NAVILE BASKET BOLOGNA', homeScore: 45, awayScore: 65, date: '2026-03-12', time: '21:50', status: 'finished', mvpVotes: 0, matchday: 17 },
    { id: 'h-m101', homeTeamId: "CLATERNA 'B' OZZANO E.", awayTeamId: 'UNDERGROUND MURRI BO', homeScore: 55, awayScore: 60, date: '2026-03-12', time: '21:30', status: 'finished', mvpVotes: 0, matchday: 17 },
    { id: 'h-m102', homeTeamId: 'BASKET VILLAGE GRANAROLO E.', awayTeamId: 'PALL. CASTEL S.P.T. 2010', homeScore: 48, awayScore: 72, date: '2026-03-13', time: '21:45', status: 'finished', mvpVotes: 0, matchday: 17 },
    // Giornata 18
    { id: 'h-m103', homeTeamId: 'P.G.S. CORTICELLA BO', awayTeamId: 'BASKET VILLAGE GRANAROLO E.', homeScore: 102, awayScore: 58, date: '2026-03-18', time: '21:15', status: 'finished', mvpVotes: 0, matchday: 18 },
    { id: 'h-m104', homeTeamId: "CLATERNA 'B' OZZANO E.", awayTeamId: 'PALL. CASTEL S.P.T. 2010', date: '2026-03-19', time: '21:30', status: 'scheduled', mvpVotes: 0, matchday: 18 },
    { id: 'h-m105', homeTeamId: 'THUNDER BASKET BO', awayTeamId: "PROGRESSO HAPPY BKT '07", date: '2026-03-19', time: '22:00', status: 'scheduled', mvpVotes: 0, matchday: 18 },
    { id: 'h-m106', homeTeamId: 'PALL. BUDRIO', awayTeamId: 'REUNION BOLOGNA', date: '2026-03-20', time: '21:45', status: 'scheduled', mvpVotes: 0, matchday: 18 },
    { id: 'h-m107', homeTeamId: 'NAVILE BASKET BOLOGNA', awayTeamId: 'PGS-IMA BOLOGNA', date: '2026-03-23', time: '21:45', status: 'scheduled', mvpVotes: 0, matchday: 18 },
    { id: 'h-m108', homeTeamId: 'STARS BASKET BOLOGNA', awayTeamId: 'UNDERGROUND MURRI BO', date: '2026-03-23', time: '21:30', status: 'scheduled', mvpVotes: 0, matchday: 18 },
    // Giornata 19
    { id: 'h-m109', homeTeamId: 'PALL. CASTEL S.P.T. 2010', awayTeamId: 'REUNION BOLOGNA', date: '2026-03-25', time: '21:15', status: 'scheduled', mvpVotes: 0, matchday: 19 },
    { id: 'h-m110', homeTeamId: 'THUNDER BASKET BO', awayTeamId: "CLATERNA 'B' OZZANO E.", date: '2026-03-26', time: '22:00', status: 'scheduled', mvpVotes: 0, matchday: 19 },
    { id: 'h-m111', homeTeamId: 'UNDERGROUND MURRI BO', awayTeamId: 'BASKET VILLAGE GRANAROLO E.', date: '2026-03-27', time: '20:50', status: 'scheduled', mvpVotes: 0, matchday: 19 },
    { id: 'h-m112', homeTeamId: 'PALL. BUDRIO', awayTeamId: 'PGS-IMA BOLOGNA', date: '2026-03-27', time: '21:45', status: 'scheduled', mvpVotes: 0, matchday: 19 },
    { id: 'h-m113', homeTeamId: 'NAVILE BASKET BOLOGNA', awayTeamId: 'STARS BASKET BOLOGNA', date: '2026-03-30', time: '21:45', status: 'scheduled', mvpVotes: 0, matchday: 19 },
    { id: 'h-m114', homeTeamId: 'PALL. CASTEL S.P.T. 2010', awayTeamId: 'P.G.S. CORTICELLA BO', date: '2026-04-01', time: '21:15', status: 'scheduled', mvpVotes: 0, matchday: 19 },
    // Giornata 20
    { id: 'h-m115', homeTeamId: "PROGRESSO HAPPY BKT '07", awayTeamId: 'REUNION BOLOGNA', date: '2026-04-02', time: '21:50', status: 'scheduled', mvpVotes: 0, matchday: 20 },
    { id: 'h-m116', homeTeamId: 'PALL. CASTEL S.P.T. 2010', awayTeamId: "PROGRESSO HAPPY BKT '07", date: '2026-04-08', time: '21:15', status: 'scheduled', mvpVotes: 0, matchday: 20 },
    { id: 'h-m117', homeTeamId: 'REUNION BOLOGNA', awayTeamId: 'P.G.S. CORTICELLA BO', date: '2026-04-09', time: '21:45', status: 'scheduled', mvpVotes: 0, matchday: 20 },
    { id: 'h-m118', homeTeamId: 'BASKET VILLAGE GRANAROLO E.', awayTeamId: 'NAVILE BASKET BOLOGNA', date: '2026-04-10', time: '21:45', status: 'scheduled', mvpVotes: 0, matchday: 20 },
    { id: 'h-m119', homeTeamId: 'PALL. BUDRIO', awayTeamId: 'THUNDER BASKET BO', date: '2026-04-10', time: '21:45', status: 'scheduled', mvpVotes: 0, matchday: 20 },
    { id: 'h-m120', homeTeamId: 'UNDERGROUND MURRI BO', awayTeamId: "CLATERNA 'B' OZZANO E.", date: '2026-04-10', time: '20:50', status: 'scheduled', mvpVotes: 0, matchday: 20 },
    { id: 'h-m121', homeTeamId: 'PGS-IMA BOLOGNA', awayTeamId: 'STARS BASKET BOLOGNA', date: '2026-04-10', time: '21:45', status: 'scheduled', mvpVotes: 0, matchday: 20 },
    // Giornata 21
    { id: 'h-m122', homeTeamId: "PROGRESSO HAPPY BKT '07", awayTeamId: "CLATERNA 'B' OZZANO E.", date: '2026-04-14', time: '21:50', status: 'scheduled', mvpVotes: 0, matchday: 21 },
    { id: 'h-m123', homeTeamId: 'UNDERGROUND MURRI BO', awayTeamId: 'THUNDER BASKET BO', date: '2026-04-17', time: '20:50', status: 'scheduled', mvpVotes: 0, matchday: 21 },
    { id: 'h-m124', homeTeamId: 'PALL. BUDRIO', awayTeamId: 'BASKET VILLAGE GRANAROLO E.', date: '2026-04-17', time: '21:45', status: 'scheduled', mvpVotes: 0, matchday: 21 },
    { id: 'h-m125', homeTeamId: 'PGS-IMA BOLOGNA', awayTeamId: "PROGRESSO HAPPY BKT '07", date: '2026-04-17', time: '21:45', status: 'scheduled', mvpVotes: 0, matchday: 21 },
    { id: 'h-m126', homeTeamId: 'P.G.S. CORTICELLA BO', awayTeamId: 'NAVILE BASKET BOLOGNA', date: '2026-04-20', time: '21:15', status: 'scheduled', mvpVotes: 0, matchday: 21 },
    { id: 'h-m127', homeTeamId: 'STARS BASKET BOLOGNA', awayTeamId: 'REUNION BOLOGNA', date: '2026-04-20', time: '21:30', status: 'scheduled', mvpVotes: 0, matchday: 21 },
    // Giornata 22
    { id: 'h-m128', homeTeamId: 'PALL. CASTEL S.P.T. 2010', awayTeamId: 'PGS-IMA BOLOGNA', date: '2026-04-22', time: '21:15', status: 'scheduled', mvpVotes: 0, matchday: 22 },
    { id: 'h-m129', homeTeamId: 'REUNION BOLOGNA', awayTeamId: 'BASKET VILLAGE GRANAROLO E.', date: '2026-04-23', time: '21:45', status: 'scheduled', mvpVotes: 0, matchday: 22 },
    { id: 'h-m130', homeTeamId: "CLATERNA 'B' OZZANO E.", awayTeamId: 'STARS BASKET BOLOGNA', date: '2026-04-23', time: '21:00', status: 'scheduled', mvpVotes: 0, matchday: 22 },
    { id: 'h-m131', homeTeamId: 'THUNDER BASKET BO', awayTeamId: 'P.G.S. CORTICELLA BO', date: '2026-04-23', time: '22:00', status: 'scheduled', mvpVotes: 0, matchday: 22 },
    { id: 'h-m132', homeTeamId: 'UNDERGROUND MURRI BO', awayTeamId: 'PALL. BUDRIO', date: '2026-04-24', time: '20:50', status: 'scheduled', mvpVotes: 0, matchday: 22 },
    { id: 'h-m133', homeTeamId: 'NAVILE BASKET BOLOGNA', awayTeamId: 'PALL. CASTEL S.P.T. 2010', date: '2026-04-27', time: '21:45', status: 'scheduled', mvpVotes: 0, matchday: 22 },
  ],
  'girone-i': [],
  'girone-l': [
    // Giornata 1
    { id: 'l-m1', homeTeamId: 'ARCOBALENO I COLORI DEL MOV. B', awayTeamId: 'MISANO PIRATES', homeScore: 63, awayScore: 60, date: '2025-11-05', time: '21:20', status: 'finished', mvpVotes: 0, matchday: 1 },
    { id: 'l-m2', homeTeamId: 'LIVIO NERI CESENA', awayTeamId: 'AROUND SPORT SAVIGNANO S/RUBIC', homeScore: 82, awayScore: 49, date: '2025-11-06', time: '21:00', status: 'finished', mvpVotes: 0, matchday: 1 },
    { id: 'l-m3', homeTeamId: 'E CRUSERI RAVENNA', awayTeamId: "A.I.C.S. BASKET FORLI'", homeScore: 68, awayScore: 61, date: '2025-11-06', time: '20:30', status: 'finished', mvpVotes: 0, matchday: 1 },
    { id: 'l-m4', homeTeamId: 'EASY LINE PALL. CESENA 2.0', awayTeamId: 'BASKERS FORLIMPOPOLI', homeScore: 51, awayScore: 63, date: '2025-11-07', time: '21:30', status: 'finished', mvpVotes: 0, matchday: 1 },
    { id: 'l-m5', homeTeamId: 'CATTOLICA NEXT GEN', awayTeamId: "AICS JUNIOR BASKET FORLI'", homeScore: 58, awayScore: 78, date: '2025-12-09', time: '21:30', status: 'finished', mvpVotes: 0, matchday: 1 },
    // Giornata 2
    { id: 'l-m6', homeTeamId: 'E CRUSERI RAVENNA', awayTeamId: 'EASY LINE PALL. CESENA 2.0', homeScore: 44, awayScore: 59, date: '2025-11-12', time: '20:30', status: 'finished', mvpVotes: 0, matchday: 2 },
    { id: 'l-m7', homeTeamId: "AICS JUNIOR BASKET FORLI'", awayTeamId: 'ARCOBALENO I COLORI DEL MOV. B', homeScore: 54, awayScore: 46, date: '2025-11-13', time: '21:15', status: 'finished', mvpVotes: 0, matchday: 2 },
    { id: 'l-m8', homeTeamId: 'MISANO PIRATES', awayTeamId: 'LIVIO NERI CESENA', homeScore: 54, awayScore: 59, date: '2025-11-14', time: '21:20', status: 'finished', mvpVotes: 0, matchday: 2 },
    { id: 'l-m9', homeTeamId: 'BASKERS FORLIMPOPOLI', awayTeamId: "A.I.C.S. BASKET FORLI'", homeScore: 60, awayScore: 36, date: '2025-11-14', time: '21:15', status: 'finished', mvpVotes: 0, matchday: 2 },
    { id: 'l-m10', homeTeamId: 'AROUND SPORT SAVIGNANO S/RUBIC', awayTeamId: 'CATTOLICA NEXT GEN', homeScore: 78, awayScore: 64, date: '2025-12-05', time: '20:30', status: 'finished', mvpVotes: 0, matchday: 2 },
    // Giornata 3
    { id: 'l-m11', homeTeamId: "A.I.C.S. BASKET FORLI'", awayTeamId: 'LIVIO NERI CESENA', homeScore: 56, awayScore: 68, date: '2025-11-20', time: '21:30', status: 'finished', mvpVotes: 0, matchday: 3 },
    { id: 'l-m12', homeTeamId: 'E CRUSERI RAVENNA', awayTeamId: "AICS JUNIOR BASKET FORLI'", homeScore: 42, awayScore: 64, date: '2025-11-20', time: '20:30', status: 'finished', mvpVotes: 0, matchday: 3 },
    { id: 'l-m13', homeTeamId: 'EASY LINE PALL. CESENA 2.0', awayTeamId: 'AROUND SPORT SAVIGNANO S/RUBIC', homeScore: 46, awayScore: 42, date: '2025-11-21', time: '21:30', status: 'finished', mvpVotes: 0, matchday: 3 },
    { id: 'l-m14', homeTeamId: 'BASKERS FORLIMPOPOLI', awayTeamId: 'MISANO PIRATES', homeScore: 76, awayScore: 58, date: '2025-11-21', time: '21:15', status: 'finished', mvpVotes: 0, matchday: 3 },
    { id: 'l-m15', homeTeamId: 'CATTOLICA NEXT GEN', awayTeamId: 'ARCOBALENO I COLORI DEL MOV. B', homeScore: 66, awayScore: 64, date: '2025-11-25', time: '21:30', status: 'finished', mvpVotes: 0, matchday: 3 },
    // Giornata 4
    { id: 'l-m16', homeTeamId: "AICS JUNIOR BASKET FORLI'", awayTeamId: 'MISANO PIRATES', homeScore: 64, awayScore: 46, date: '2025-11-27', time: '21:15', status: 'finished', mvpVotes: 0, matchday: 4 },
    { id: 'l-m17', homeTeamId: 'LIVIO NERI CESENA', awayTeamId: 'BASKERS FORLIMPOPOLI', homeScore: 47, awayScore: 69, date: '2025-11-27', time: '21:00', status: 'finished', mvpVotes: 0, matchday: 4 },
    { id: 'l-m18', homeTeamId: 'AROUND SPORT SAVIGNANO S/RUBIC', awayTeamId: 'E CRUSERI RAVENNA', homeScore: 54, awayScore: 60, date: '2025-11-28', time: '20:30', status: 'finished', mvpVotes: 0, matchday: 4 },
    { id: 'l-m19', homeTeamId: 'CATTOLICA NEXT GEN', awayTeamId: 'EASY LINE PALL. CESENA 2.0', homeScore: 74, awayScore: 65, date: '2025-11-28', time: '21:30', status: 'finished', mvpVotes: 0, matchday: 4 },
    { id: 'l-m20', homeTeamId: "A.I.C.S. BASKET FORLI'", awayTeamId: 'ARCOBALENO I COLORI DEL MOV. B', homeScore: 56, awayScore: 49, date: '2025-12-03', time: '21:30', status: 'finished', mvpVotes: 0, matchday: 4 },
    // Giornata 5
    { id: 'l-m21', homeTeamId: 'EASY LINE PALL. CESENA 2.0', awayTeamId: 'LIVIO NERI CESENA', homeScore: 58, awayScore: 51, date: '2025-12-05', time: '21:30', status: 'finished', mvpVotes: 0, matchday: 5 },
    { id: 'l-m22', homeTeamId: 'BASKERS FORLIMPOPOLI', awayTeamId: "AICS JUNIOR BASKET FORLI'", homeScore: 52, awayScore: 58, date: '2025-12-05', time: '21:15', status: 'finished', mvpVotes: 0, matchday: 5 },
    { id: 'l-m23', homeTeamId: 'MISANO PIRATES', awayTeamId: 'E CRUSERI RAVENNA', homeScore: 59, awayScore: 56, date: '2025-12-05', time: '21:20', status: 'finished', mvpVotes: 0, matchday: 5 },
    { id: 'l-m24', homeTeamId: 'ARCOBALENO I COLORI DEL MOV. B', awayTeamId: 'AROUND SPORT SAVIGNANO S/RUBIC', homeScore: 45, awayScore: 54, date: '2025-12-10', time: '21:20', status: 'finished', mvpVotes: 0, matchday: 5 },
    { id: 'l-m25', homeTeamId: 'CATTOLICA NEXT GEN', awayTeamId: "A.I.C.S. BASKET FORLI'", homeScore: 46, awayScore: 52, date: '2025-12-12', time: '21:30', status: 'finished', mvpVotes: 0, matchday: 5 },
    // Giornata 6
    { id: 'l-m26', homeTeamId: 'LIVIO NERI CESENA', awayTeamId: 'CATTOLICA NEXT GEN', homeScore: 70, awayScore: 47, date: '2025-12-11', time: '21:00', status: 'finished', mvpVotes: 0, matchday: 6 },
    { id: 'l-m27', homeTeamId: 'E CRUSERI RAVENNA', awayTeamId: 'BASKERS FORLIMPOPOLI', homeScore: 36, awayScore: 55, date: '2025-12-11', time: '20:30', status: 'finished', mvpVotes: 0, matchday: 6 },
    { id: 'l-m28', homeTeamId: 'AROUND SPORT SAVIGNANO S/RUBIC', awayTeamId: "AICS JUNIOR BASKET FORLI'", homeScore: 59, awayScore: 56, date: '2025-12-12', time: '20:30', status: 'finished', mvpVotes: 0, matchday: 6 },
    { id: 'l-m29', homeTeamId: 'EASY LINE PALL. CESENA 2.0', awayTeamId: 'ARCOBALENO I COLORI DEL MOV. B', homeScore: 49, awayScore: 57, date: '2025-12-12', time: '21:30', status: 'finished', mvpVotes: 0, matchday: 6 },
    { id: 'l-m30', homeTeamId: "A.I.C.S. BASKET FORLI'", awayTeamId: 'MISANO PIRATES', homeScore: 49, awayScore: 30, date: '2025-12-17', time: '21:30', status: 'finished', mvpVotes: 0, matchday: 6 },
    // Giornata 7
    { id: 'l-m31', homeTeamId: 'ARCOBALENO I COLORI DEL MOV. B', awayTeamId: 'LIVIO NERI CESENA', homeScore: 50, awayScore: 63, date: '2025-12-17', time: '21:20', status: 'finished', mvpVotes: 0, matchday: 7 },
    { id: 'l-m32', homeTeamId: 'BASKERS FORLIMPOPOLI', awayTeamId: 'AROUND SPORT SAVIGNANO S/RUBIC', homeScore: 75, awayScore: 65, date: '2025-12-19', time: '21:15', status: 'finished', mvpVotes: 0, matchday: 7 },
    { id: 'l-m33', homeTeamId: 'MISANO PIRATES', awayTeamId: 'EASY LINE PALL. CESENA 2.0', homeScore: 65, awayScore: 68, date: '2025-12-19', time: '21:20', status: 'finished', mvpVotes: 0, matchday: 7 },
    { id: 'l-m34', homeTeamId: 'CATTOLICA NEXT GEN', awayTeamId: 'E CRUSERI RAVENNA', homeScore: 54, awayScore: 57, date: '2025-12-19', time: '21:30', status: 'finished', mvpVotes: 0, matchday: 7 },
    { id: 'l-m35', homeTeamId: "AICS JUNIOR BASKET FORLI'", awayTeamId: "A.I.C.S. BASKET FORLI'", homeScore: 72, awayScore: 52, date: '2025-12-22', time: '21:15', status: 'finished', mvpVotes: 0, matchday: 7 },
    // Giornata 8
    { id: 'l-m36', homeTeamId: "AICS JUNIOR BASKET FORLI'", awayTeamId: 'LIVIO NERI CESENA', homeScore: 52, awayScore: 55, date: '2026-01-08', time: '21:15', status: 'finished', mvpVotes: 0, matchday: 8 },
    { id: 'l-m37', homeTeamId: 'MISANO PIRATES', awayTeamId: 'AROUND SPORT SAVIGNANO S/RUBIC', homeScore: 65, awayScore: 45, date: '2026-01-09', time: '21:20', status: 'finished', mvpVotes: 0, matchday: 8 },
    { id: 'l-m38', homeTeamId: 'EASY LINE PALL. CESENA 2.0', awayTeamId: "A.I.C.S. BASKET FORLI'", homeScore: 54, awayScore: 42, date: '2026-01-09', time: '21:30', status: 'finished', mvpVotes: 0, matchday: 8 },
    { id: 'l-m39', homeTeamId: 'BASKERS FORLIMPOPOLI', awayTeamId: 'CATTOLICA NEXT GEN', homeScore: 57, awayScore: 37, date: '2026-01-09', time: '21:15', status: 'finished', mvpVotes: 0, matchday: 8 },
    { id: 'l-m40', homeTeamId: 'E CRUSERI RAVENNA', awayTeamId: 'ARCOBALENO I COLORI DEL MOV. B', homeScore: 38, awayScore: 47, date: '2026-01-13', time: '20:30', status: 'finished', mvpVotes: 0, matchday: 8 },
    // Giornata 9
    { id: 'l-m41', homeTeamId: 'LIVIO NERI CESENA', awayTeamId: 'E CRUSERI RAVENNA', homeScore: 60, awayScore: 50, date: '2026-01-15', time: '21:00', status: 'finished', mvpVotes: 0, matchday: 9 },
    { id: 'l-m42', homeTeamId: 'CATTOLICA NEXT GEN', awayTeamId: 'MISANO PIRATES', homeScore: 59, awayScore: 71, date: '2026-01-16', time: '21:30', status: 'finished', mvpVotes: 0, matchday: 9 },
    { id: 'l-m43', homeTeamId: 'AROUND SPORT SAVIGNANO S/RUBIC', awayTeamId: "A.I.C.S. BASKET FORLI'", homeScore: 61, awayScore: 67, date: '2026-01-16', time: '20:30', status: 'finished', mvpVotes: 0, matchday: 9 },
    { id: 'l-m44', homeTeamId: 'EASY LINE PALL. CESENA 2.0', awayTeamId: "AICS JUNIOR BASKET FORLI'", homeScore: 62, awayScore: 61, date: '2026-01-16', time: '21:30', status: 'finished', mvpVotes: 0, matchday: 9 },
    { id: 'l-m45', homeTeamId: 'ARCOBALENO I COLORI DEL MOV. B', awayTeamId: 'BASKERS FORLIMPOPOLI', homeScore: 45, awayScore: 60, date: '2026-01-19', time: '21:20', status: 'finished', mvpVotes: 0, matchday: 9 },
    // Giornata 10 (Ritorno)
    { id: 'l-m46', homeTeamId: "A.I.C.S. BASKET FORLI'", awayTeamId: 'E CRUSERI RAVENNA', homeScore: 56, awayScore: 50, date: '2026-01-21', time: '21:30', status: 'finished', mvpVotes: 0, matchday: 10 },
    { id: 'l-m47', homeTeamId: "AICS JUNIOR BASKET FORLI'", awayTeamId: 'CATTOLICA NEXT GEN', homeScore: 72, awayScore: 46, date: '2026-01-22', time: '21:15', status: 'finished', mvpVotes: 0, matchday: 10 },
    { id: 'l-m48', homeTeamId: 'BASKERS FORLIMPOPOLI', awayTeamId: 'EASY LINE PALL. CESENA 2.0', homeScore: 52, awayScore: 40, date: '2026-01-23', time: '21:15', status: 'finished', mvpVotes: 0, matchday: 10 },
    { id: 'l-m49', homeTeamId: 'MISANO PIRATES', awayTeamId: 'ARCOBALENO I COLORI DEL MOV. B', homeScore: 46, awayScore: 51, date: '2026-01-23', time: '21:20', status: 'finished', mvpVotes: 0, matchday: 10 },
    { id: 'l-m50', homeTeamId: 'AROUND SPORT SAVIGNANO S/RUBIC', awayTeamId: 'LIVIO NERI CESENA', homeScore: 47, awayScore: 60, date: '2026-01-23', time: '20:30', status: 'finished', mvpVotes: 0, matchday: 10 },
    // Giornata 11
    { id: 'l-m51', homeTeamId: 'ARCOBALENO I COLORI DEL MOV. B', awayTeamId: "AICS JUNIOR BASKET FORLI'", homeScore: 44, awayScore: 57, date: '2026-01-28', time: '21:20', status: 'finished', mvpVotes: 0, matchday: 11 },
    { id: 'l-m52', homeTeamId: "A.I.C.S. BASKET FORLI'", awayTeamId: 'BASKERS FORLIMPOPOLI', homeScore: 54, awayScore: 64, date: '2026-01-28', time: '21:30', status: 'finished', mvpVotes: 0, matchday: 11 },
    { id: 'l-m53', homeTeamId: 'LIVIO NERI CESENA', awayTeamId: 'MISANO PIRATES', homeScore: 68, awayScore: 64, date: '2026-01-29', time: '21:00', status: 'finished', mvpVotes: 0, matchday: 11 },
    { id: 'l-m54', homeTeamId: 'EASY LINE PALL. CESENA 2.0', awayTeamId: 'E CRUSERI RAVENNA', homeScore: 56, awayScore: 37, date: '2026-01-30', time: '21:30', status: 'finished', mvpVotes: 0, matchday: 11 },
    { id: 'l-m55', homeTeamId: 'CATTOLICA NEXT GEN', awayTeamId: 'AROUND SPORT SAVIGNANO S/RUBIC', homeScore: 56, awayScore: 36, date: '2026-01-30', time: '21:30', status: 'finished', mvpVotes: 0, matchday: 11 },
    // Giornata 12
    { id: 'l-m56', homeTeamId: "AICS JUNIOR BASKET FORLI'", awayTeamId: 'E CRUSERI RAVENNA', homeScore: 69, awayScore: 32, date: '2026-02-05', time: '21:15', status: 'finished', mvpVotes: 0, matchday: 12 },
    { id: 'l-m57', homeTeamId: 'LIVIO NERI CESENA', awayTeamId: "A.I.C.S. BASKET FORLI'", homeScore: 53, awayScore: 56, date: '2026-02-05', time: '21:00', status: 'finished', mvpVotes: 0, matchday: 12 },
    { id: 'l-m58', homeTeamId: 'AROUND SPORT SAVIGNANO S/RUBIC', awayTeamId: 'EASY LINE PALL. CESENA 2.0', homeScore: 52, awayScore: 71, date: '2026-02-06', time: '20:30', status: 'finished', mvpVotes: 0, matchday: 12 },
    { id: 'l-m59', homeTeamId: 'MISANO PIRATES', awayTeamId: 'BASKERS FORLIMPOPOLI', homeScore: 40, awayScore: 45, date: '2026-02-06', time: '21:20', status: 'finished', mvpVotes: 0, matchday: 12 },
    { id: 'l-m60', homeTeamId: 'ARCOBALENO I COLORI DEL MOV. B', awayTeamId: 'CATTOLICA NEXT GEN', homeScore: 57, awayScore: 66, date: '2026-02-11', time: '21:20', status: 'finished', mvpVotes: 0, matchday: 12 },
    // Giornata 13
    { id: 'l-m61', homeTeamId: 'E CRUSERI RAVENNA', awayTeamId: 'AROUND SPORT SAVIGNANO S/RUBIC', homeScore: 38, awayScore: 60, date: '2026-02-12', time: '20:30', status: 'finished', mvpVotes: 0, matchday: 13 },
    { id: 'l-m62', homeTeamId: 'BASKERS FORLIMPOPOLI', awayTeamId: 'LIVIO NERI CESENA', homeScore: 64, awayScore: 57, date: '2026-02-13', time: '21:15', status: 'finished', mvpVotes: 0, matchday: 13 },
    { id: 'l-m63', homeTeamId: 'MISANO PIRATES', awayTeamId: "AICS JUNIOR BASKET FORLI'", homeScore: 38, awayScore: 66, date: '2026-02-13', time: '21:20', status: 'finished', mvpVotes: 0, matchday: 13 },
    { id: 'l-m64', homeTeamId: 'EASY LINE PALL. CESENA 2.0', awayTeamId: 'CATTOLICA NEXT GEN', homeScore: 63, awayScore: 43, date: '2026-02-13', time: '21:30', status: 'finished', mvpVotes: 0, matchday: 13 },
    { id: 'l-m65', homeTeamId: 'ARCOBALENO I COLORI DEL MOV. B', awayTeamId: "A.I.C.S. BASKET FORLI'", homeScore: 55, awayScore: 65, date: '2026-02-16', time: '21:20', status: 'finished', mvpVotes: 0, matchday: 13 },
    // Giornata 14
    { id: 'l-m66', homeTeamId: "AICS JUNIOR BASKET FORLI'", awayTeamId: 'BASKERS FORLIMPOPOLI', homeScore: 49, awayScore: 42, date: '2026-02-16', time: '21:15', status: 'finished', mvpVotes: 0, matchday: 14 },
    { id: 'l-m67', homeTeamId: 'LIVIO NERI CESENA', awayTeamId: 'EASY LINE PALL. CESENA 2.0', homeScore: 52, awayScore: 88, date: '2026-02-19', time: '21:00', status: 'finished', mvpVotes: 0, matchday: 14 },
    { id: 'l-m68', homeTeamId: 'E CRUSERI RAVENNA', awayTeamId: 'MISANO PIRATES', homeScore: 52, awayScore: 71, date: '2026-02-19', time: '20:30', status: 'finished', mvpVotes: 0, matchday: 14 },
    { id: 'l-m69', homeTeamId: 'AROUND SPORT SAVIGNANO S/RUBIC', awayTeamId: 'ARCOBALENO I COLORI DEL MOV. B', homeScore: 67, awayScore: 73, date: '2026-02-20', time: '20:30', status: 'finished', mvpVotes: 0, matchday: 14 },
    { id: 'l-m70', homeTeamId: "A.I.C.S. BASKET FORLI'", awayTeamId: 'CATTOLICA NEXT GEN', homeScore: 52, awayScore: 50, date: '2026-02-20', time: '21:00', status: 'finished', mvpVotes: 0, matchday: 14 },
    // Giornata 15
    { id: 'l-m71', homeTeamId: 'ARCOBALENO I COLORI DEL MOV. B', awayTeamId: 'EASY LINE PALL. CESENA 2.0', homeScore: 52, awayScore: 58, date: '2026-02-25', time: '21:20', status: 'finished', mvpVotes: 0, matchday: 15 },
    { id: 'l-m72', homeTeamId: "AICS JUNIOR BASKET FORLI'", awayTeamId: 'AROUND SPORT SAVIGNANO S/RUBIC', homeScore: 75, awayScore: 39, date: '2026-02-26', time: '21:15', status: 'finished', mvpVotes: 0, matchday: 15 },
    { id: 'l-m73', homeTeamId: 'BASKERS FORLIMPOPOLI', awayTeamId: 'E CRUSERI RAVENNA', homeScore: 74, awayScore: 63, date: '2026-02-27', time: '21:15', status: 'finished', mvpVotes: 0, matchday: 15 },
    { id: 'l-m74', homeTeamId: 'MISANO PIRATES', awayTeamId: "A.I.C.S. BASKET FORLI'", homeScore: 59, awayScore: 69, date: '2026-02-27', time: '21:20', status: 'finished', mvpVotes: 0, matchday: 15 },
    { id: 'l-m75', homeTeamId: 'CATTOLICA NEXT GEN', awayTeamId: 'LIVIO NERI CESENA', date: '2026-03-24', time: '21:30', status: 'scheduled', mvpVotes: 0, matchday: 15 },
    // Giornata 16
    { id: 'l-m76', homeTeamId: "A.I.C.S. BASKET FORLI'", awayTeamId: "AICS JUNIOR BASKET FORLI'", homeScore: 43, awayScore: 51, date: '2026-03-04', time: '21:30', status: 'finished', mvpVotes: 0, matchday: 16 },
    { id: 'l-m77', homeTeamId: 'E CRUSERI RAVENNA', awayTeamId: 'CATTOLICA NEXT GEN', homeScore: 51, awayScore: 60, date: '2026-03-05', time: '20:30', status: 'finished', mvpVotes: 0, matchday: 16 },
    { id: 'l-m78', homeTeamId: 'LIVIO NERI CESENA', awayTeamId: 'ARCOBALENO I COLORI DEL MOV. B', homeScore: 65, awayScore: 67, date: '2026-03-05', time: '21:00', status: 'finished', mvpVotes: 0, matchday: 16 },
    { id: 'l-m79', homeTeamId: 'EASY LINE PALL. CESENA 2.0', awayTeamId: 'MISANO PIRATES', homeScore: 77, awayScore: 40, date: '2026-03-06', time: '21:30', status: 'finished', mvpVotes: 0, matchday: 16 },
    { id: 'l-m80', homeTeamId: 'AROUND SPORT SAVIGNANO S/RUBIC', awayTeamId: 'BASKERS FORLIMPOPOLI', homeScore: 48, awayScore: 66, date: '2026-03-06', time: '20:30', status: 'finished', mvpVotes: 0, matchday: 16 },
    // Giornata 17
    { id: 'l-m81', homeTeamId: "A.I.C.S. BASKET FORLI'", awayTeamId: 'EASY LINE PALL. CESENA 2.0', homeScore: 63, awayScore: 70, date: '2026-03-11', time: '21:30', status: 'finished', mvpVotes: 0, matchday: 17 },
    { id: 'l-m82', homeTeamId: 'ARCOBALENO I COLORI DEL MOV. B', awayTeamId: 'E CRUSERI RAVENNA', homeScore: 59, awayScore: 48, date: '2026-03-11', time: '21:20', status: 'finished', mvpVotes: 0, matchday: 17 },
    { id: 'l-m83', homeTeamId: 'LIVIO NERI CESENA', awayTeamId: "AICS JUNIOR BASKET FORLI'", homeScore: 49, awayScore: 63, date: '2026-03-12', time: '21:00', status: 'finished', mvpVotes: 0, matchday: 17 },
    { id: 'l-m84', homeTeamId: 'CATTOLICA NEXT GEN', awayTeamId: 'BASKERS FORLIMPOPOLI', homeScore: 63, awayScore: 67, date: '2026-03-13', time: '21:30', status: 'finished', mvpVotes: 0, matchday: 17 },
    { id: 'l-m85', homeTeamId: 'AROUND SPORT SAVIGNANO S/RUBIC', awayTeamId: 'MISANO PIRATES', homeScore: 47, awayScore: 73, date: '2026-03-13', time: '20:30', status: 'finished', mvpVotes: 0, matchday: 17 },
    // Giornata 18
    { id: 'l-m86', homeTeamId: "AICS JUNIOR BASKET FORLI'", awayTeamId: 'EASY LINE PALL. CESENA 2.0', date: '2026-03-19', time: '21:15', status: 'scheduled', mvpVotes: 0, matchday: 18 },
    { id: 'l-m87', homeTeamId: 'E CRUSERI RAVENNA', awayTeamId: 'LIVIO NERI CESENA', date: '2026-03-19', time: '20:30', status: 'scheduled', mvpVotes: 0, matchday: 18 },
    { id: 'l-m88', homeTeamId: 'BASKERS FORLIMPOPOLI', awayTeamId: 'ARCOBALENO I COLORI DEL MOV. B', date: '2026-03-20', time: '21:15', status: 'scheduled', mvpVotes: 0, matchday: 18 },
    { id: 'l-m89', homeTeamId: 'MISANO PIRATES', awayTeamId: 'CATTOLICA NEXT GEN', date: '2026-03-20', time: '21:20', status: 'scheduled', mvpVotes: 0, matchday: 18 },
    { id: 'l-m90', homeTeamId: "A.I.C.S. BASKET FORLI'", awayTeamId: 'AROUND SPORT SAVIGNANO S/RUBIC', date: '2026-03-25', time: '21:30', status: 'scheduled', mvpVotes: 0, matchday: 18 }
  ]
};
